apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hatchet-frontend-api
  namespace: stage
spec:
  parentRefs:
    - name: traefik-gw
      namespace: kube-system
  hostnames:
    - "hatchet.stage.mstrat.fund"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              replacePrefixMatch: /
      backendRefs:
        - name: hatchet-stage-api
          port: 8080
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: hatchet-stage-frontend
          port: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hatchet-engine
  namespace: stage
spec:
  parentRefs:
    - name: traefik-gw
      namespace: kube-system
  hostnames:
    - "engine.hatchet.stage.mstrat.fund"
  rules:
    - backendRefs:
        - name: hatchet-stage-engine
          port: 7070
